Hero section
temporalio/temporaldotio pull request #44
Opened 2021-08-12 15:32 UTC by m-abdelwahab

# Before

![image](https://user-images.githubusercontent.com/27310414/129224253-0b89ef32-59fb-4231-b930-5224a952a2bb.png)

# After

![image](https://user-images.githubusercontent.com/27310414/129224852-52d60d01-0503-4769-9dd8-948f9429f667.png)

# Changes

1. Change button border-radius
2. Updated GH CTA
3. Navbar resizing
4. Code Switcher that adds context when hovering
5. Change title casing for readability
6. Add logos section along with links to case studies

2021-08-12 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/temporalio/temporaldotio?pullRequest=44) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/temporalio/temporaldotio?pullRequest=44) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/temporalio/temporaldotio?pullRequest=44) it.</sub>

2021-08-12 16:52 UTC, sw-yx commented on components/Companies.js
> +        <span className="opacity-75">Check out case studies from</span>{' '}
technically the rest of these are not case studies

```suggestion
        <span className="opacity-75">Check out more from</span>{' '}
```

2021-08-12 16:54 UTC, sw-yx commented on components/Companies.js
> +              className="w-32 h-32 md:w-36 lg:w-44 md:h-36 lg:h-44"
can we do something on hover? this is an svg so we can color it in with `currentColor`

suggestion

```suggestion
          <a key={i} className="hover:text-temporalblue" href={site.url}>
```

2021-08-12 16:54 UTC, sw-yx commented on components/Companies.js
> +        Trusted in production by
```suggestion
        Trusted by
```

2021-08-12 16:56 UTC, sw-yx commented on components/Companies.js
> +];
can you also add zebra medical vision and airbyte logos pls

```suggestion
  {
    src: '/logos/logo-Descript.svg',
    alt: 'Descript logo',
    url: 'https://docs.temporal.io/blog/descript-case-study'
  },
  {
    src: '/logos/logo-Zebra.svg',
    alt: 'Zebra logo',
    url: 'https://docs.temporal.io/blog/zebra-medical-case-study'
  },
  {
    src: '/logos/logo-Airbyte.svg',
    alt: 'Airbyte logo',
    url: 'https://docs.temporal.io/blog/airbyte-case-study'
  }
];
```

2021-08-12 16:58 UTC, sw-yx commented on components/Hero.js
> +            </div>
Suggestion

```suggestion
            <p>
              <a href="https://github.com/temporalio/temporal" rel="noreferrer" target="_blank">
                Open Source + Self Hostable
              </a>
            </p>
```

2021-08-12 16:59 UTC, sw-yx commented on components/Hero.js
> +            <DirectionalControl href="#explain-temporal">Get Started</DirectionalControl>
```suggestion
            <DirectionalControl href="#explain-temporal">2 Minute Video</DirectionalControl>
```

2021-08-12 17:00 UTC, sw-yx requested changes

2021-08-12 17:00 UTC, sw-yx commented on components/Hero.js
> +              How it works
same link why

2021-08-12 17:02 UTC, m-abdelwahab commented on components/Hero.js
> +              How it works
typo

2021-08-12 17:06 UTC, feedmeapples commented
the three window dots.. they are quite bright and stand out from the rest of the page when don't seem to have a purpose?

![image](https://user-images.githubusercontent.com/11838981/129238396-3ebb151a-dcd3-4a5c-b7b5-48cb9fc4eb3b.png)

2021-08-12 17:08 UTC, m-abdelwahab commented
> the three window dots.. they are quite bright and stand out from the rest of the page when don't seem to have a purpose?
> 
> ![image](https://user-images.githubusercontent.com/11838981/129238396-3ebb151a-dcd3-4a5c-b7b5-48cb9fc4eb3b.png)

@feedmeapples so they're supposed to make the tab component look more like a window, similar to VSCode. For the colors, I can definitely pick a darker color

2021-08-12 17:16 UTC, feedmeapples commented
> @feedmeapples so they're supposed to make the tab component look more like a window, similar to VSCode. For the colors, I can definitely pick a darker color

i do like the lines indexes and lang tab buttons a lot! Still not sure about the pseudo-buttons even if they are darker. Code-block components are quite common and imho windowish enough while minimal.
Then there is also extra blank space. Imho if the tab buttons were at the top of the code block would look super slick
![image](https://user-images.githubusercontent.com/11838981/129239825-b2a6d619-4c62-4c85-bd08-2159852f5d13.png)

2021-08-12 17:20 UTC, feedmeapples commented
Looks good!

2021-08-12 17:24 UTC, sw-yx commented on components/CodeSwitcher/CodeSwitcher.js
> +            <p>Node</p>
we are rebranding to TypeScript

```suggestion
            <p>TypeScript</p>
```

can you make sure to change in the rest of the code

2021-08-12 19:29 UTC, m-abdelwahab commented on components/Companies.js
> +];
Sure! 👍🏻

2021-08-12 19:29 UTC, m-abdelwahab commented on components/CodeSwitcher/CodeSwitcher.js
> +            <p>Node</p>
Rebranding to TS makes a lot of sense

2021-08-13 15:29 UTC, sw-yx commented on components/Companies.js
> +        </a>
```suggestion
        <span className="opacity-75">Check out more from</span>{' '}
        <a
          className="nav-link"
          href="https://eng.snap.com/build_a_reliable_system_in_a_microservices_world_at_snap/">
          Snap
        </a>
        ,{' '}
        <a
          className="nav-link"
          href="https://www.youtube.com/watch?v=kDlrM6sgk2k&t=1188s&ab_channel=HashiCorp">
          Hashicorp
        </a>
        ,{' '}
        <a
          className="nav-link"
          href="https://www.youtube.com/watch?v=eWFpl-nzGsY&feature=youtu.be">
          Datadog
        </a>
        ,{' '}
        <a
          className="nav-link"
          href="https://doordash.engineering/2020/08/14/workflows-cadence-event-driven-processing/">
          Doordash
        </a>{' '}
        &{' '}
        <a className="nav-link" href="https://docs.temporal.io/docs/external-resources">
          others
        </a>
```

2021-08-13 15:39 UTC, sw-yx commented on components/Hero.js
> +              <p className="font-medium">2210</p>
```suggestion
```

2021-08-13 15:41 UTC, sw-yx commented on components/Companies.js
> +              className="w-32 h-32 md:w-44 md:h-44"
```suggestion
              className="w-32 h-32 md:w-44 md:h-44 hover:text-temporalblue"
```

2021-08-13 15:41 UTC, sw-yx commented on public/logos/logo-Zebra-Medical-Vision.svg
> +<svg width="300" height="300" viewBox="0 0 300 300" fill="none"
```suggestion
<svg width="300" height="300" viewBox="0 0 300 300" fill="currentColor"
```

2021-08-13 15:41 UTC, sw-yx commented on public/logos/logo-Descript.svg
> +<svg width="300" height="300" viewBox="0 0 300 300" fill="none"
```suggestion
<svg width="300" height="300" viewBox="0 0 300 300" fill="currentColor"
```

2021-08-13 15:42 UTC, sw-yx commented on public/logos/logo-Coinbase.svg
> +<svg width="300" height="300" viewBox="0 0 300 300" fill="none"
```suggestion
<svg width="300" height="300" viewBox="0 0 300 300" fill="currentColor"
```

2021-08-13 15:42 UTC, sw-yx commented on public/logos/logo-Checkr.svg
> +<svg width="300" height="300" viewBox="0 0 300 300" fill="none"
```suggestion
<svg width="300" height="300" viewBox="0 0 300 300" fill="currentColor"
```

2021-08-13 15:42 UTC, sw-yx commented on public/logos/logo-Box.svg
> +<svg width="300" height="300" viewBox="0 0 300 300" fill="none"
```suggestion
<svg width="300" height="300" viewBox="0 0 300 300" fill="currentColor"
```

2021-08-13 15:42 UTC, sw-yx commented on public/logos/logo-Airbyte.svg
> +<svg width="300" height="300" viewBox="0 0 300 300" fill="none"
```suggestion
<svg width="300" height="300" viewBox="0 0 300 300" fill="currentColor"
```

2021-08-13 18:18 UTC, merged